# Generated by Django 5.2.7 on 2025-12-24 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('field', models.CharField(choices=[('IT', 'INFORMATION TECHNOLOGY'), ('NON IT', 'NON INFORMATION TECHNOLOGY')], max_length=8)),
                ('image', models.ImageField(upload_to='demo_proj/')),
            ],
        ),
    ]
