# Generated by Django 5.2.7 on 2025-12-24 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeedetails',
            name='employee_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
